[package]
name = "downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.7.0"
reqwest = "0.11.14"
bytes = "1.3.0"
url = "2.3.1"
infer = "0.12.0"